version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elvja
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/elvja?schema=public
      PORT: 3000
    volumes: ["./backend:/app"]
    working_dir: /app
    command: sh -c "npm ci && npx prisma generate && npm run start:dev"
    ports: ["3000:3000"]
    depends_on: [db, redis]
  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
    volumes: ["./frontend:/app"]
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    ports: ["5173:5173"]
  proxy:
    image: nginx:1.27
    depends_on: [ frontend, backend ]
    ports: ["80:80"]
volumes: { pgdata: {} }
